################################################################
#
# Pipeline pipeline_16s_db.py configuration file 
# Add pipeline specific options into separate sections
#
################################################################
## general options

# Project name
projectname: pipeline_16s_db

# Copyright statement
copyright: jethro johnson

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

database: csvdb

mbscriptsdir: /gpfs3/well/johnson/users/ovz380/devel/scripts/microbiome_scripts

################################################################
# Location of input files and databases
location:
    assembly_summary: ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/assembly_summary.txt

    ncbi_taxonomy: /gpfs3/well/johnson/shared/databases/ncbi_taxonomy/211214/

################################################################
# Criteria for selecting genomes to download 
# This will be appended to SQL statement following WHERE
genomes:
    selection: refseq_category=='reference genome' OR refseq_category=='representative genome' 